### ISSUE TITLE
--@sharedscreen breaks the upload

### ISSUE THREAD

**Issue by wraith321** [INPStarfall/Starfall#132]
When using --@sharedscreen in a screen, no further screens / processors can be used ("wait for the current upload to finish")

**Comment by wraith321** [comment]
I just saw that screens run serverside by default, was --@sharedscreen removed? Even then it still breaks the screen

**Comment by Xandaros** [comment]
That explains why it was happening to me, but not to you^^
Fixed by 8b2264c1559c086938bbe789a6291a5595d1505d

And no, screens don't run serverside by default. They, however, have some serverside code.
