### ISSUE TITLE
Find better name for wire.createIn-/Outputs

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#146]
The name is misleading. It suggests adding new In-/Outputs while it is in fact overwriting the current ones.
If I first create inputs A and B and then C and D, I am left with only C and D.

**Comment by awilliamson** [comment]
I vote for naming it exactly as Wire named theirs. ...AdjustSpecialOutputs and ...AdjustSpecialInputs. Obviously fix the casing. Might also want to document the onLoad function as that actually creats the inputs and outputs for the chip.

EDIT: adjustInputs and adjustOutputs I'd be all for.
