### ISSUE TITLE
error when printing wrapped render polys

### ISSUE THREAD

**Issue by shawnkoh** [INPStarfall/Starfall#152]
render = loadLibrary("render")
printTable( render.createPoly({
    {x=1, y=2},
    {x=3, y=4}
}))

errors
addons/starfall/lua/starfall/libs_sh/builtins.lua:280: table index is nil

**Comment by Xandaros** [comment]
The problem here is that trying to get the length (#) of a compiled poly always returns 0, I think.

Now sure why you'd want to print a compiled poly, though. It is compiled, after all.
