### ISSUE TITLE
sf_defaultquota is not properly shared

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#17]
For some reason, sf_defaultquota is not properly shared between clients

**Comment by awilliamson** [comment]
Is this still occurring. Noticed that it seemed to share just fine when we updated it on INP. Any steps to show the difference or reproduction scenario?

EDIT: New players that join won't have the updated convar I believe.

**Comment by awilliamson** [comment]
@Skraay is still having this issue, @Xandaros mentions that his convar says 1 million when the server is set to 100k.

**Comment by awilliamson** [comment]
Is now irrelevant #215
