### ISSUE TITLE
Modify SF.Unwrap

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#171]
Have some sflib function which will unwrap an object IF it can, otherwise it passes through the normal value. This would be useful for type metamethods where you can't possible account for every type of object, such as __eq.

EDIT: function SF.Unsanitize does this I believe, more testing required.

**Comment by Xandaros** [comment]
Unsanitize works on tables instead of individual values, but it does it for every entry in the table.

**Comment by awilliamson** [comment]
As pointed out by @Xandaros during our converstaion. Generally when you're wrapping/unwrapping you know what types you're converting to/from. When you're trying to unwrap in the general sense you usually are doing so on a table of values, and as pointed out you can use Sanitize/Unsanitize, alternatively do `SF.Unwrap( val ) or val` if you really need to return the original if it can't unwrap.
