### ISSUE TITLE
os.date( string format, number time ) - How to ?

### ISSUE THREAD

**Issue by RoboLV** [INPStarfall/Starfall#177]
I have a problem.
Is there way to use os.date or dateformat ?

**Comment by Xandaros** [comment]
I don't think that is currently possible, but needs to be added.

(Sorry for the late reply, GitHub decided I don't need to get an E-Mail about it and I had a milestone filter active, so it didn't appear in my issue list)

**Comment by awilliamson** [comment]
Fixed by #205 You now do exactly as it says on the GMod Wiki.http://wiki.garrysmod.com/page/Category:os
