### ISSUE TITLE
Get rid of loadLibrary

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#178]
loadLibrary just causes redundant code and doesn't really do anything. It just returns the library.

If you have a look at the stock libraries, they are all in the global namespace. The same in other languages.

If anything belongs in the global namespace, it is libraries. It's not like we are putting functions or variables there, we are putting libraries, collections of functions there.

**Comment by awilliamson** [comment]
Even though I like things separate, I understand that even Lua uses the global namespace to put things like table and math libraries in. I guess my reluctance stems from E2's all-in-the-soup approach. I guess this is a good change, and if servers modify SF and add their own system libraries, and it gets cluttered or named incorrectly then it's their own mess.

I'd say get rid of loadLibrary, even though I don't want to, I know it's for the best. I'm sick of writing loadLibrary in my SF code :D
