### ISSUE TITLE
Add G.LocalToWorld and G.WorldToLocal functions

### ISSUE THREAD

**Issue by AlexanderArvidsson** [INPStarfall/Starfall#186]
These 2 functions are useful, what more can I say :D
Before anyone gets confused, I do not mean the ent_methods:localToWorld, I mean the global ones.

http://wiki.garrysmod.com/page/Global/LocalToWorld
http://wiki.garrysmod.com/page/Global/WorldToLocal

**Comment by awilliamson** [comment]
Why do we need these as global functions? They're pretty easy if you have an understanding of how vectors work?

**Comment by AlexanderArvidsson** [comment]
Yes, but from what I've read up on them, you'd need matrices to rewrite them, and I don't even know if starfall has that.
Either way, it would be much easier to just implement them, doesn't need to be global, just needs to accept the same arguments.

**Comment by Xandaros** [comment]
You don't need matrices for that.
Just subtract the origin of the new coordinate system from your vector and you are good to go. Simple as that, just subtraction.
For LocalToWorld, you just do the opposite - adding.

And Starfall does have matrices, but they are used for rendering on the screen.

**Comment by AlexanderArvidsson** [comment]
Wrong, you need to take into account the angles! Those two functions doesn't only use positions, the angles rotate it around, which would be easier to do with matrices.

**Comment by wraith321** [comment]
``` lua
local function transformWorldToLocal(position, angle, localPos, localAngle)
    local lPos = position - localPos
    lPos:Rotate(-localAngle)
    local lAng = angle - localAngle

    return lPos, lAng
end

local function transformLocalToWorld(position, angle, localPos, localAngle)
    --Vector:Rotate does not return a new Vector, so we copy the position first
    --to avoid altering the external position
    local wPos = Vector(position.x, position.y, position.z)
    wPos:Rotate(localAngle)
    wPos = wPos + localPos
    local wAng = angle + localAngle

    return wPos, wAng
end
```

As easy as that :).

**Comment by AlexanderArvidsson** [comment]
The toWorld function you provided works fine, thanks for that!
But the toLocal one doesn't quite work as expected. It works when you have pitch and roll on 0, and only rotating yaw, but after that it goes all wonky and rotates the position wrongly.
I can't really explain it, but if you do some testing yourself, you might find the same issue.

**Comment by Xandaros** [comment]
I don't see anything wrong with it, but I didn't try it.
Point is, it can be done in starfall and there is no need to add it as/to a system library.
I might make an official user library with convenience functions like this, but it won't be shipped with starfall and needs to be downloaded manually.

**Comment by AlexanderArvidsson** [comment]
I compared it to garry's function, but who knows which is the correct one.
Anyway, they don't work the same way on certain angles
