### ISSUE TITLE
serverinfo.maxPlayers backing function is nil

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#187]
serverinfo.getMaxPlayers tried to call serverinfo.MaxPlayer (GLua), which does not exist.
It should be game.MaxPlayers

I also suggest changing the name to getMaxPlayers.

**Comment by awilliamson** [comment]
We should probably rename a lot of the old standing funcs that use the old E2 naming system.

**Comment by awilliamson** [comment]
Fixed by 6152d5a
