### ISSUE TITLE
Add pack/unpack

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#193]
Just noticed that pack/unpack are missing, these are potentially very useful functions provided by Lua so should be in the default environment.

EDIT - Packing seems to work by just wrapping a function which returns multiple values in curly braces, and only just found the unwrap function in default environment. Perhaps we need to actually give the pack global func.

EDIT2 - It seems that pack as a global doesn't seem to exist in 5.1. I'm sure I remember using pack/unpack when writing Lua. There are table.pack and table.unpack in 5.2. Now GLua is a mix of 5.1 and 5.2 as IRC garry cherrypicked some features from 5.2 to update.

**Comment by Xandaros** [comment]
`unpack` is definitely available in starfall, I've used it before. `pack` doesn't even exist in Lua.
There is table.pack, though(In Lua 5.2), but I don't see the point of it...
