### ISSUE TITLE
Print Table issue

### ISSUE THREAD

**Issue by Jazzelhawk** [INPStarfall/Starfall#198]
This is the printTable function

``` lua
function SF.DefaultEnvironment.printTable( tbl )
    if CLIENT and SF.instance.player ~= LocalPlayer() then return end
    SF.CheckType( tbl, "table" )

    printTableX( (SERVER and SF.instance.player or LocalPlayer()), tbl, 0, {[t] = true} )
end
```

When printTableX is used the `alreadyprinted` arg is `{[t] = true}`
I don't really know why t is set like [t] or what it is even used for but when it is done like that it gives a table index is nil error. To fix this the arg should just be changed to `{t = true}`

**Comment by Xandaros** [comment]
I can see that happening.
But I wonder... how has it ever worked?
See https://github.com/INPStarfall/Starfall/commit/983d684f2f6a75cc7cc72bbeb42e71f6b2de778e
Has always been that way…

**Comment by Jazzelhawk** [comment]
Yea that's what I was wondering about. Seems pretty odd how it has worked all this time xD
