### ISSUE TITLE
Coroutines for Starfall processors.

### ISSUE THREAD

**Issue by daranable** [INPStarfall/Starfall#2]
Wrap all Starfall processors in coroutines.  Allowing for pausing and resuming of scripts using the coroutines.

**Comment by Xandaros** [comment]
@daranable Would you mind if I do this after the permissions? You seem to be busy and coroutines would make it so much better.
I'm also planning on adding a coroutine library. I looked into it and it doesn't seem too hard to secure.

**Comment by Xandaros** [comment]
Well... some further testing has revealed that the interaction between debug.sethook and coroutines seems to be buggy.
If you error in debug.sethook, it will stop execution as expected. However, hooks will not get called again, even after setting new ones and unsetting it before calling error)

Edit: nevermind, after starting with a fresh file, it works. I have no idea what I am doing different. Going to figure that out, though.

**Comment by daranable** [comment]
So as far as you taking this, I will talk to you more in depth about this.  There is a lot to do that isn't very straight forward for this.  I will talk to you this weekend about it.
