### ISSUE TITLE
Holo scale is not set properly most of the time

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#20]
Holograms usually don't scale during creation or even when using SetScale directly after creation.
Sometimes you get clientside errors, although I have no idea why you usually don't get any errors.

**Comment by awilliamson** [comment]
Could be related to the rate of the holograms spawning, as we still encounter occasional instances where data isn't correctly transferred because things update too quickly ( or so it seems ).

Eg. The sync test SF script, sometimes clients see just 0 because the number wasn't sent to them in time.

**Comment by Xandaros** [comment]
I know exactly why that error happens, I don't get why the scale is sometimes not set properly even though there is no error.
I'll debug that tomorrow

**Comment by Xandaros** [comment]
Apparently this is not fixed, it still happens occasionally. (Though a lot rarer)
