### ISSUE TITLE
Color==Color not working

### ISSUE THREAD

**Issue by NotAkitake** [INPStarfall/Starfall#212]
Not sure if this counts in #189 but I've been quite annoyed by something lately.

if Color(255,0,0)==Color(255,0,0) then
    print("true")
else print("false") end

prints false.
(From what I've seen it just looks like Color doesn't have any function related to it yet, so that means no equal function either I suppose, but just in case that still shouldn't happen I wanted to point it out)

I'd actually really like to be able to do the above to detect ground in 2D games below the character, instead of having to seperately store r,g,b values and put them back together when drawing.

**Comment by awilliamson** [comment]
See #34

It sort of counts, color is implemented in builtin and we just wrap it. We don't do what we've done with the other types which is to define a load of methods and metamethods. However, the __eq metamethod can easily be added from within SF I believe, then this would allow you to compare them in whichever way you want.
