### ISSUE TITLE
The new Vector type can't be divided by numbers

### ISSUE THREAD

**Issue by wraith321** [INPStarfall/Starfall#216]
I think this should be added to the Vector type, so that the following is valid again:

Vector(1, 1, 1) / 2 == Vector(0.5, 0.5, 0.5)

**Comment by Xandaros** [comment]
Dividing a vector by another vector doesn't make sense. Dividing a vector by a scalar, does.

**Comment by wraith321** [comment]
That's exactly what I meant with this issue ^^. Vector by Vector division isn't needed

**Comment by awilliamson** [comment]
Perhaps we'll add this. Until then multiply by fractions. Using the div metamethod you would get a lot of check type exceptions so I'd like to add extra functionality to that check so we can have functions for operators that won't give odd errors that are useless to the user.

**Comment by wraith321** [comment]
Isn't it actually the same to the user if he tries to divide a Vector at the moment, which isn't possible at all - or with invalid types, if it were possible with numbers?

**Comment by Xandaros** [comment]
> That's exactly what I meant with this issue ^^. Vector by Vector division isn't needed

I know. There was another comment I was referencing, but it appears it has been deleted.
