### ISSUE TITLE
There is currently no way of getting a player's aimEntity.

### ISSUE THREAD

**Issue by NotAkitake** [INPStarfall/Starfall#217]
The title speaks for itself.
There is no implementation of Player:GetEyeTrace() yet (I checked players.lua, docs, and did a bunch of tests to make sure).

**Comment by AlexanderArvidsson** [comment]
Starfall has a trace library, you can use that.
But having a function for the player eye trace would definately be acceptable!

**Comment by Xandaros** [comment]
Eye trace is more efficient, since it is automatically done every tick.

**Comment by awilliamson** [comment]
Fixed by #246, 542aef5
