### ISSUE TITLE
Metamethod __div is missing from Vector type

### ISSUE THREAD

**Issue by AlexanderArvidsson** [INPStarfall/Starfall#220]
Title says it all.
And please don't tell me you're not adding it because it's easy enough to just make a function that does it, because we already have __mul, __sub, _add, etc.

**Comment by wraith321** [comment]
#216 ^^

**Comment by AlexanderArvidsson** [comment]
Oh, woops, didn't see that, sorry. I'll close this issue and let yours live on.
