### ISSUE TITLE
Mul Vectors

### ISSUE THREAD

**Issue by RoboLV** [INPStarfall/Starfall#222]
Hello!
I have this problem:
I try to mul vectors ( Vector(2,2,2) \* Vector(3,4,5) == Vector( 6,8,10) ) 
But i got ERROR:
"starfall/RayTraceX.txt:73: Type mismatch (Expected number, got Vector) in function __mul"
Code :
------------------------------------- vector-------number-------num--------vector
73 : local color = Vector(255,255,255)*(1-tr.Fraction) \* Box \* Vector(255,155,0)

**Comment by awilliamson** [comment]
There are more than two ways to do vector - vector multiplication. Using the mul metamethod only accepts vector-number multiplication or multiplication by a scalar.

**Comment by RoboLV** [comment]
Ok,then show me the way, to mul vectors without creating any aditional metods.
For example this task :  Vector(2,2,2) \* Vector(3,4,5) \* 10

**Comment by Xandaros** [comment]
There are many ways to multiply two vectors, the most common ones are cross and dot product, which we provide methods for.
If you need to do some weird multiplication (like component-wise, as you appear to be doing), you will need to define that yourself. We can't handle every corner case.
