### ISSUE TITLE
How do you get components of an angle?

### ISSUE THREAD

**Issue by sirdabalot** [INPStarfall/Starfall#224]
Sorry this is probably such a stupid question but I've looked everywhere and tried everything, even using ang[ 1 ] in the same way you get vector components, but nothing's working, how do I do this?

**Comment by sirdabalot** [comment]
Found after a little more searching on previous issues xD My apologies, closing now. If anyone else is wondering its ang.p .y .r

**Comment by Xandaros** [comment]
If ang[1] is not working, we might want to add that, I'll reopen the issue for now.
