### ISSUE TITLE
Starfall Editor animation occasionally seen through map brushes.

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#23]
Some people have reported seeing the falling stars animation through map brushes. I haven't seen this behaviour. If anybody has screenshots feel free to post them below, and if you can narrow down the criteria such as what type of brushes, angles, etc that would be great.

**Comment by Xandaros** [comment]
I recently saw the same happen with E2 and lemon gate. I think this is garrys fault.
