### ISSUE TITLE
holo:setColor

### ISSUE THREAD

**Issue by glebqip** [INPStarfall/Starfall#253]
Is holo:setColor work? I can't change a color on holos(no errors).

**Comment by awilliamson** [comment]
It works fine. In the future when making an issue, please provide more information. Code that you're using that causes the issue, perhaps some investigation of your own to try and narrow the problem.

Try looking at this:

``` lua
--@name Holograms Example for @glebqip
--@author Radon

local holo = holograms.create( entities.self():getPos(), Angle(0, 0, 0), "models/props_borealis/bluebarrel001.mdl", Vector(0.5,0.5,0.5))

hook.add("Think", "Think", function()
    holo:setPos( entities.self():getPos() + Vector(0,0,100) + Vector(35*math.cos(timer.curtime()), 35*math.sin(timer.curtime()), 0 ))
    holo:setColor( Color( math.random( 0, 255 ), math.random( 0, 255 ), math.random( 0, 255 ) ) ) 
end)
```

This should produce a barrel, which rotates above the chip, whilst changing color. If it does not, please ensure you have an up to date version of Starfall, after all of this please consider reopening this information with adequate information.
