### ISSUE TITLE
No sound.emitEntity?

### ISSUE THREAD

**Issue by glebqip** [INPStarfall/Starfall#257]

**Comment by wraith321** [comment]
Use [sounds.create ( ent, path )](https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/libs_sh/sounds.lua)

**Comment by glebqip** [comment]
Loop sounds plays one time?

**Comment by awilliamson** [comment]
If the sounds don't automatically loop, then consider checking if the sound isPlaying and if not, play again. I tested some loops sounds when making the library, generator sounds to be precise, and they seemed to loop fine.

**Comment by glebqip** [comment]
EmitSound plays all sounds once, but sound.create():play() plays sound as a loop.
And i can play more than 1 same sound.
