### ISSUE TITLE
Can you create a DataSignals?

### ISSUE THREAD

**Issue by glebqip** [INPStarfall/Starfall#259]

**Comment by wraith321** [comment]
Use the [net library](http://sf.inp.io/libraries/net.html)

**Comment by glebqip** [comment]
Net library can't send information to another SERVER chip...

**Comment by awilliamson** [comment]
http://sf.inp.io/libraries/hook.html#hook_library.runRemote remote hook execution, we've had it for a while. Reading the documentation of the net library from the official docs may prove useful to you.
