### ISSUE TITLE
Color values can't be changed

### ISSUE THREAD

**Issue by wraith321** [INPStarfall/Starfall#282]
``` lua
local test = Color(255,255,255,255)
print(test)
test.r = 1
print(test)
print(test.r)
```

result:
255 255 255 255
255 255 255 255
1

**Comment by awilliamson** [comment]
iirc, rawset should be working as expected. I will do some testing later as I'd certainly prefer the elegance of a single line than a lot of checks.

Color[1] should work. And maybe Color["r"].
