### ISSUE TITLE
Code isn't running as shared?

### ISSUE THREAD

**Issue by thegrb93** [INPStarfall/Starfall#294]
```
if SERVER then
    print("Server")
else
    s.b()
    print("Client")
end
```

I expect a runtime error, but nothing is being run on the client.

Okay, I found the problem. Starfall processor runs server-side only. Aren't the file and sound components client-side? How do I use those with the processor? I guess I can use the screen but I don't need the screen.

**Comment by Xandaros** [comment]
File at least is shared, but you will probably get a permission denied error on most servers if you try to use it on server side.
