### ISSUE TITLE
Find library filter type check

### ISSUE THREAD

**Issue by Jazzelhawk** [INPStarfall/Starfall#315]
There is only one type check for the filters in the find library apart from the inBox function which seems to do it properly. [line 34 - find.lua](https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/libs_sh/find.lua#L34)

And the level is set to 1 in the type check but it doesn't lead to a helpful error message:
`addons/starfall/lua/starfall/instance.lua:37: Type mismatch (Expected function, got table) in function func`

It should say something like:
`generic:4: Type mismatch (Expected function, got table) in function all`

I'd also suggest changing the description of the filter to mention the parameter of the filter function

**Comment by thegrb93** [comment]
Unrelated, but is the find cooldown necessary? I've always wondered that. I think the cpu quota is enough. I think I might remove that cooldown if nobody has any good reason for it.

**Comment by awilliamson** [comment]
@Jazzelhawk Is this issue resolved? If so, please close.
