### ISSUE TITLE
Editor clipboard hang on Linux

### ISSUE THREAD

**Issue by Jazzelhawk** [INPStarfall/Starfall#339]
So when you paste something into a DHTML panel on Linux the game hangs and this is particularly annoying when pasting in a model string for the new model preprocessor statement. 

So I thought a decent solution would be to make a sort of model selector ( like the prop menu ) so that when you click on a model it inserts the model string into the editor where the writing cursor is currently located.
My first thought is to have a new button to open a new window popup and when you click on a model it inserts the string and closes the window. The button would be disabled by default for non-linux users but would be able to turn it on through the settings window.
@awilliamson Pointed out that a keybind and/or having the window open automatically when typing in
`--@model` might be useful?

@Xandaros Any thoughts/suggestions?

**Comment by Xandaros** [comment]
Having a window like that would probably be a good idea, but I disagree with the button being disabled for non-Linux users. For all we know, Mac has the same problem and overall it would be confusing to have different feature sets depending on OS. (Even if you can turn it on in settings)

Instead, just have it available to everyone. Closing the editor, navigating the spawn menu, etc. is annoying as it is. If this menu manages to make it better, everybody wins.

As for automatically open it when typing `--@model`... no. NO. NO! NOOOOOOOOO!
Did I make my opinion clear yet? NO!
That's like the worst feature I have ever heard proposed. lol
