### ISSUE TITLE
SF editor not working for non UK/US Keyboard layouts

### ISSUE THREAD

**Issue by suunr** [INPStarfall/Starfall#344]
Ctrl-Q and AltGr-Q close the editor. But in german and other keyboard layouts AltGr-Q types a @ (at). So if you type AltGr-Q with german keyboard layout the editor closes and no @ gets typed.
Is there also any way to get old editor back? The new one is buggy, behaves strange, less configurable, laggier and crashes my game (it sucks).

**Comment by Jazzelhawk** [comment]
I can add a setting to disable the Ctrl-Q keybind. 

The reason I made a new editor is to move Starfall away from the Wiremod dependency so it is not certain that we will add support for the wiremod editor.
Could you elaborate on how the editor is buggy, strange behaviour and crashes? What are your suggestions to make the editor more configurable?

**Comment by suunr** [comment]
Why should it be independent from wiremod? Starfall doesnt work without wiremod, making a new editor is useless.

Some things i miss in configuration:
- setting tab size
- changing colors of keywords or other elements
- disabling wrapping of lines

I know that they're missing in the e2 editor too, but insteand of making a new editor, it would be better to focus on the existing one.

The DHTML panel didn't appear sometimes (white box). It could be only fixed by restarting game. There werent any lua errors.

There's a problem with another keybind too. AltGr-0 toggles folding, but on german keyboard layout it's uses to type in }.

**Comment by Xandaros** [comment]
> Starfall doesnt work without wiremod

You're right, it doesn't. But it should. Apart from the wire library, there is conceptually nothing tying starfall to wiremod, so why should it not work without it? Replacing the editor is but one step in the direction of independence, but a very important one. The editor is what was holding us back the most, the only calls to wiremod left are, to my knowledge, the rendering on the screens.

(Also, the E2 editor is a mess. Just look at the code. It's horrible. There is no way we are going to change anything in that. You add the ability to change the colour of keywords and suddenly the validation doesn't work any more or something like that. No thanks. Using it before was too hacky for comfort already...)

**Comment by Xandaros** [comment]
AltGr+Q doesn't close the editor for me, even with the quit keybind enabled, but when I type }, for example (AltGr+0), it does some folding stuff.
The editor, as it is, is useless with a German keyboard layout. Please make sure that your keybinds don't activate with AltGr. (Registered as both Ctrl and Alt, I think)

It also seems like undo is Ctrl+Y instead of Ctrl+Z, which... well, the E2 editor does the same, but it is weird :D

**Comment by Jazzelhawk** [comment]
AltGr + Q shouldn't close the editor, the keybind is Ctrl + Q. Try that.
The AltGr+0 thing is fixed in this PR #359.
Other than that, any keybinds I have added don't use AltGr and the only keybinds on Ace which use Alt+Key are the folding ones ( which will be fixed in that PR )
