### ISSUE TITLE
Remake VMatrix Lib. Fix SF.CheckType's

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#36]
Remove SF.CheckType( self, vmatrix_metamethods ).
Fix other SF.CheckType as they use "Number" and "Angle" which are incorrect.

EDIT: Fix __mul metamethod.

**Comment by Xandaros** [comment]
What's wrong with the VMatrix lib?

**Comment by awilliamson** [comment]
Most use-cases for matricies tend to be using the passthrough 'Matrix'. Haven't seen anybody using VMatrix yet, I've only ever used them for 3D rendering in GMod gamemodes. If anybody has any sample code to test the library that would be nice.

A bug also exists where the __mul metamethod for the VMatrix lib is doing rhs_rhs rather than lhs_lhs. Also checking the current type to be it's metamethods is pointless, also checking the lbs of any two-sided operation from metamethods is also pointless as it's guaranteed to be of the type specified.
