### ISSUE TITLE
~ still not working on some keyboards

### ISSUE THREAD

**Issue by Damianu** [INPStarfall/Starfall#372]
I can't type ~ using polish keyboard layout in starfall. It opens console and doesnt write char. When I switch my key laout to english one it writes char but still opens console( I was trying with and without fix enabled)

**Comment by Jazzelhawk** [comment]
I don't think there is anything I can do about this as it's most likely something to do with GMod internally opening the console.

**Comment by davidsonbr** [comment]
You could change your console bind, or disable it.

~~I don't think this has anything to do with the SF editor though. I'll see if the E2 editor behaves the same way.~~

Edit: typing ` opens console. ~ on the other hand types ~. This is the default behavior outside any editors. So contrary to my previous beliefs, this is something to do with our editor.

**Comment by Jazzelhawk** [comment]
For a UK Keyboard layout ` opens the console for me but for example on a US layout I have to press Shift + ` which types a ~ to open the console. If I switch to a Polish keyboard layout I press Shift + ` to type a ~ which does not open the console. But if you find a text box on the GMod menu ( Start New Game and then there is one in the bottom left ) and try to type the ~ on the Polish layout it opens the console without typing the ~. Therefore this is not something to do with our editor as it happens in GMod on its own with HTML panels.

If you want to make an issue on the garrysmod issues page feel free (https://github.com/Facepunch/garrysmod-issues) but I suspect this is something similar to the issue I opened a while ago (https://github.com/Facepunch/garrysmod-issues/issues/1941).

**Comment by davidsonbr** [comment]
I rebound my console key to HOME to test its behavior.
- Outside of all editors
  - Pressing the HOME key results in console opening
  - Pressing Shift / Ctrl / Alt + HOME does not result in the console opening
- In E2 editor
  - Pressing the HOME key results in the home function being executed inside the editor; no console
  - Pressing Shift / Ctrl / Alt + HOME does not results in the proper function being executed; no console
- In the SF editor
  - Pressing the HOME key results in the home function **not** being executed inside the editor; console opened
  -  Pressing Shift / Ctrl / Alt + HOME results in function **not** being executed; console opening

Rebound console key back to `
- Outside of all editors
  - ` results in console opening
  - Shift / Ctrl / Alt + ` ( ~ ) results in console not opening
- In E2 editor
  - ` results in console opening
  - Shift / Ctrl / Alt + ` ( ~ ) results in console not opening; 
  - Shift + ` pressed results in "~" being typed.
- In the SF editor
  - ` results in console opening and being closed ( fix console bug enabled & disabled )
  - Shift / Ctrl / Alt + ` ( ~ ) results in console opening
  - Shift + ` pressed results in "~" being typed.

This has to do with the Starfall Editor.

**Comment by Jazzelhawk** [comment]
This is nothing to do with console keybinds, it is to do with HTML panels. 
You didn't even try the Polish keyboard layout... As I said Shift + ` types ~ on a Polish layout and does not open the console normally. Find a HTML panel which you can type into ( A standard one in GMod is the one on the Start New Game menu ) and press Shift + ` (~). It opens the console even though it is not a keybind.
Technically this is to do with the editor since it uses a HTML panel but there is nothing I can do about it unless it is fixed in the actual game.
