### ISSUE TITLE
Creating many timers results in crash

### ISSUE THREAD

**Issue by suunr** [INPStarfall/Starfall#373]
``` lua
--@sharedscreen
if CLIENT then
  local i = 0
  function t ()
    i = i + 1
    timer.create( tostring( i ), 0.1, 0, t )
  end
  t()
end
```

Running this code will crash player clients. I didn't try it out serverside yet, but I think it will result in a crash too.
Maybe there should be some limit of timers?

**Comment by Jazzelhawk** [comment]
I think you missed out something like `i = i + 1`. But yeah this needs to be sorted out as the amount of timers grows exponentially. I think the functions run by timers are not being checked for cpuTime properly therefore there is no CPU Quota being exceeded.

**Comment by suunrider** [comment]
Is it really only checking cpu time after execution? A program which writes to 10 cells in a highspeed device already exceeded CPU Quota.
