### ISSUE TITLE
Last commit weird quota behaviour

### ISSUE THREAD

**Issue by Damianu** [INPStarfall/Starfall#376]
I was working on my script using screens all the day, then I tested it - avg cpu time about 15% on hard use. Now after update it has 50% on idle.. I am not even doing something hard to render or whatever.. As I saw networking was taking much more cpu time than before.

**Comment by awilliamson** [comment]
Cpu time checking wasn't accurate before. We've added additional checks to catch edge cases that slipped through causing unexpected bugs. It won't be that it's 'using' more than it was before, just that it's more accurately representing this to you.

CPU Quota-ing chips should be more stable now, at least that's my current hypothesis.

**Comment by Xandaros** [comment]
It was not counting everything properly before. You will notice it to be a lot harsher now, because it is actually running properly :)

**Comment by Damianu** [comment]
That's the thing, it randomly crashes. It does same every render frame, sometimes crashes after one second, sometimes work few minutes without hard quota..

**Comment by awilliamson** [comment]
`( quotaUsed() < quotaMax() ) and ( quotaAverage() < quotaMax * 0.9 )`

Try the above as a quota function ( used in conjunction with coroutines ). In the brief testing done tonight, ships seem more stable. But obviously that's limited to what I've tried which is mainly prime number sieves on a processor.

**Comment by Damianu** [comment]
http://i.imgur.com/P3Umf6B.png Code from examples for displaying quota + clear now has 3% of average usage, isn't it too much for such simple render of text?

**Comment by awilliamson** [comment]
quotaUsed might be displaying 0 because you're calling the check from a 'render' hook. You need to gain data from 'think' and only display in 'render'.

**Comment by Damianu** [comment]
Yeah, but it's the only code I used. Just example to see if simple 4 texts renders would have high average quota. 3% is too high for rendering 4 lines of texts on screen..

PS.Also for "better" counting. When you enable flashlight it's showing 2x more avg %(7-10).
Code I used for testing:http://pastebin.com/S1n3U50s.

**Comment by awilliamson** [comment]
Fixed by #403
