### ISSUE TITLE
Spelling mistake in codestyle guidelines

### ISSUE THREAD

**Issue by suunr** [INPStarfall/Starfall#377]
"Use spaces before the argument list of a function definition.
E.g. `fuction func ( var1, var2 ).`"
A "n" is missing.

**Comment by Jazzelhawk** [comment]
To add to this there is also this part:
local tbl2 = { "Multi-line", 2, lastVal }
which is not in a code block.

**Comment by awilliamson** [comment]
Wondered how long until somebody noticed it in an issue. It's been known for a while, not too critical.
