### ISSUE TITLE
Higher max quota?

### ISSUE THREAD

**Issue by Damianu** [INPStarfall/Starfall#382]
Since quota is counted "right" I think that default max quota should be a bit higher.Because some scripts(wchich werent lagging or something) don't work now... So yeah, I really think increasing it a bit would be awesome and shouldn't be cause of lags.

**Comment by awilliamson** [comment]
Just change the value of `sf_timebuffer`. If you find a value that seems fine you can suggest it. There's always a risk of setting a default too high. Obviously the higher the limit, and the higher the number of players, the more impact will have on the server without quota'ing.

**Comment by Damianu** [comment]
Well I tested it already before, and 0.006 - 0.007 quota is like previous 0.004(in my scripts). And client quota 0.04 is working ok(if its too much you can try 0.035). I was testing it on 16 players running my script made before quota fix. I saw not even little lag(even when it was 100%), as for clients I asked few ppl to run that command on clientside and even people with really shitty PCs were fine.
So yeah, you can test it yourself if you need to. I also hope people will post their opinios here too..

**Comment by suunrider** [comment]
Some of the examples in data/starfall/examples aren't working anymore too.

**Comment by awilliamson** [comment]
Hmm, ok. I will look into this today and aim to get the new quota pushed within the day.

**Comment by Damianu** [comment]
Yeah just make sure to not test it on some simple scripts so fancy rendering would be possible(getting opinion of someone with lowend pc would be cool too so it wont be too high).

**Comment by suunrider** [comment]
Please hurry up. None of my scripts work and starfall is unusable for me.

**Comment by davidsonbr** [comment]
read the comments before you say this is unusable.
`sf_timebuffer 0.006` in console until it is fixed

**Comment by awilliamson** [comment]
@suunrider Apologies, I've been a little busy with other more pressing bugs. As @EpicG suggested, just change the convar. It exists for a reason. `0.006` seems fine to me. It's mainly whether that value would suffice for server owners and their typical load. As a default, it could probably be pushed even higher, as I noticed plenty of room to spare when testing ( But I run a pretty empty, powerful server ).

**Comment by suunrider** [comment]
Other bugs? What is more important that it doesn't work? Locking model viewer makes window unreachable? Too huge json files which don't do anything?
You should focus more on that issue than the editor. Why would i care about an editor bug when i can't even run scripts properly?
@awilliamson, there's also a reason why I didn't use it. Not every server can do "sf_timebuffer 0.006" from day to day.
It's not admins job to get it work, it's yours.

**Comment by awilliamson** [comment]
@suunrider Watch your tone. Cpu time has convars for the exact reason that admins can change the config or that value and it will automatically update the value in real-time, no restart required. Yes, it may be a mild inconvenience to run this multiple times. When I say I have other pressing bugs, I really do.

Would you prefer me to leave a bug which breaks cpuTime checking altogether? I'm sure you'd complain if somebody could do `while true do end` and kill every client on the server? Would you rather I focus on some default value for you?

The reason the extent of that bug is not reported, is because it's too dangerous to fully report. So quit acting like a child, and be patient.

**EDIT:** It seems @suunrider has deleted their comment. In summary, it was an aggressive comment outlining that we're not focusing on the right things, and that this issue is the most critical issue.

Quote:

> Other bugs? What is more important that it doesn't work? Locking model viewer makes window unreachable? Too huge json files which don't do anything?
> You should focus more on that issue than the editor. Why would i care about an editor bug when i can't even run scripts properly?
> @awilliamson, there's also a reason why I didn't use it. Not every server can do "sf_timebuffer 0.006" from day to day.
> It's not admins job to get it work, it's yours.

**Comment by davidsonbr** [comment]
@suunrider You don't need to type `sf_timebuffer 0.006` in console every time you start.

If you are the admin, insert it into your GarrysMod/garrysmod/cfg/server.cfg file.

If you just play, ask an admin to change it. They will probably ask why to which you would respond with `https://github.com/INPStarfall/Starfall/issues/382`
