### ISSUE TITLE
Editor Shenanigans

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#383]
Latest 'few' editor tweaks left me with odd behaviour in the editor. Certain broken cursor positions or input/output behaviour.

`[HTML] Uncaught TypeError: Cannot call method 'setScrollSpeed' of undefined`

This is causing the editor to be completely unusable. Treating insert as a copy/paste selection, then a copy/paste selection in multiple places. Unable to backspace. Ugh, it's a nightmare :c @Jazzelhawk ^^

**Comment by davidsonbr** [comment]
Getting this too now.

reconnecting solved the problem, unsure of what I did before it happened. :/
