### ISSUE TITLE
Add burst & standard rate convars to hologram lib.

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#41]
Requested by Shadowscion. Thought this was already in, but must have only added the quotas for holograms.

**Comment by ColonelThirtyTwo** [comment]
I don't see the point of a 'burst' mechanic to hologram spawn limiting. A simple n-holograms-per-second quota is fine.

**Comment by Xandaros** [comment]
The idea behind the burst rate is, that holograms usually get spawned in bursts. Especially on initial spawn, people often spawn a lot of holograms at once and then never spawn any again.

For example: If you build something with holograms, you want to spawn it as quick as possible, but you don't want to spawn any holograms afterwards. But there are also cases where you want to continuously spawn holograms.
The burst mechanic is for the first use case, so those people can spawn their stuff more quickly. Of course, if they have more holograms than the burst allows, they have to spawn them a bit slower after the initial boost, but they still get the boost.

**Comment by ColonelThirtyTwo** [comment]
But is that worth the complexity of implementing a burst limiter? IMO I don't really think it is.

**Comment by Xandaros** [comment]
Where is  the problem with it? It's already implemented if you mean that, Radon just forgot to make the rate adjustable by providing a convar, that's what this is about.

**Comment by ColonelThirtyTwo** [comment]
Oh, I didn't realize it was already implemented.
