### ISSUE TITLE
Code uneditable.

### ISSUE THREAD

**Issue by ghost** [INPStarfall/Starfall#424]
Another editor bug. 
I am unable to edit whatever code I have. Backspace has the same effect as left arrow key, and I am unable to type new characters. Shortcuts such as CTRL+C and CTRL+V work. 

There's some text at the bottom of the editor that says "(recording)[]" that might have something to do with it.

Thanks.
(I believe I tried reinstalling, via deleting the file from the addons folder)

**Comment by Jazzelhawk** [comment]
The text at the bottom of the editor sounds like you may have enabled macro recording. Looking at https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts the keybind to start that is "Ctrl-Alt-E" so try pressing it again and see if that works.

**Comment by ghost** [comment]
Closing this issue. I grew impatient and reinstalled my game. Hopefully it won't reoccur. Thanks and sorry I couldn't find the problem for you guys to fix, though it's likely what Jazzelhawk suggested.

**Comment by awilliamson** [comment]
@UNST4BL3 I'd just like to point out that GitHub issues aren't for the short of '24/7 live support' issues. @Jazzelhawk responded within 9 minutes originally. It helps if you work with us in finding the cause of your problem. I understand it can be frustrating, but if somebody else looks at this issue, they won't find a solution, and that doesn't help anybody. So by spending a little time working together we can improve it for everyone :)
