### ISSUE TITLE
Holograms are being rendered twice

### ISSUE THREAD

**Issue by shadowscion** [INPStarfall/Starfall#44]
`ENT.RenderGroup = RENDERGROUP_BOTH`

Setting the render group to 'both' when the hologram is opaque causes the hologram to be rendered twice, drastically reducing clientside fps. 

Also, the alpha component of setColor does not work for entities or holograms.

**Comment by ColonelThirtyTwo** [comment]
I don't think rendering the hologram models twice is seriously hurting performance. It's not like they are complex models.

The line was probably copied from E2 holograms. It may have a reason to be in both render groups, but then again, it may not.

**Comment by Xandaros** [comment]
Even if it doesn't hurt performance too much, if it isn't necessary, it isn't necessary, is it? :)

**Comment by shadowscion** [comment]
@ColonelThirtyTwo Uhhh... I must be imagining the 50% fps boost I get when I set the rendergroup to opaque then. Not everyone has a great computer, and that's only exacerbated by how lousy gmod 13 runs compared to previous versions (no multicore processing or rendering, aswell as useless html overlays draining fps). Trust me, it hurts performance in a huge way, especially when using non default models (which is the only reason for using holos in the first place; lets face it, the default models are pointless).

It doesn't have to be on both render groups, the issue was already fixed with e2 holograms a few months back; they only need to be set to both if the hologram's color has less than 255 alpha.

**Comment by ColonelThirtyTwo** [comment]
> I must be imagining the 50% fps boost I get when I set the rendergroup to opaque then.

 I agree that it shouldn't be in both render groups if it doesn't need to be, but I doubt that statistic is accurate.

FPS is not a good scale for benchmarking because it's an inverse scale; the difference in rendering time between 1000 and 6000 FPS is much less than the difference between 1 FPS and 60 FPS. So the 50% statistic can mean anything.

Also, didn't they add multicore rendering a long time ago? (Not that it would help if your computer is as bad as you claim)

**Comment by shadowscion** [comment]
@ColonelThirtyTwo 

Multicore was available in gmod12, but removed in gmod13 (the setting is there but it doesn't do anything). According to garry, it caused instability, so instead of fixing it he just removed it and fucked everyone over.

I realize fps isnt a good benchmark, but its what we have.

Looking at empty map: 210fps

Looking at 100 "hq_sphere" models in one location:
• 87 fps with rendergroup_opaque
• 42 fps with rendergroup_both

Looking at 200 "hq_sphere" models in one location:
• 42 fps with rendergroup_opaque
• 22 fps with rendergroup_both

Looking at 300 "hq_sphere" models in one location:
• 30 fps with rendergroup_opaque
• 15 fps with rendergroup_both

Obviously these are extreme values due to the detail of the "hq_sphere" model, and it wouldn't have much of an effect if you are just using a few holograms here and there, but many people use a lot more than that.

**Comment by awilliamson** [comment]
I'd just like to point out that fps is heavily dependant on client hardware and even gmod launch settings. Standard hologram models and hq models aren't packaged with starfall we use just prop models currently if i recall correctly. In depth analytics are pointless to compare the render groups. Unless spawning excess amounts of holograms the effects will be negligible on modern up to date hardware with common settings and resolutions. 

If we can increase efficiency by stopping them rendering twice if they don't need to be then that is what we will do as @Xandaros said.

**Comment by Xandaros** [comment]
How does this relate to #24?

**Comment by ColonelThirtyTwo** [comment]
Ah, that makes sense. In the opaque pass, the hologram is drawn with its alpha ignored, so when it tries to draw itself in the transparency pass, there's already an object there, so it doesn't render anything.
