### ISSUE TITLE
Automatic Document Generation

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#65]
Work on using the Github API to tell Seth to regenerate the docs at http://sf.inp.io

**Comment by awilliamson** [comment]
Progress has been made. We've been able to retrieve repo information through a php script on seth. LuaDoc source has been downloaded and its dependencies installed on the machine. Just a few tweaks need to be made to existing create scripts to get the documentation generating I do believe.

**Comment by Xandaros** [comment]
done
