### ISSUE TITLE
Add 'masks' to trace library.

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#80]
Work on some system to add the masks to traces using ENUM from wiki.

Discussion required as to the format of how the ENUMs should be presented.
Eg trace.enum["MASK_WATER"] following name conventions outlined in GMod docs ( probably engine docs too )
Eg trace.mask.water where you replace underscore with dot and lowercase.

Thoughts?

**Comment by Xandaros** [comment]
> and lowercase

That was never part of the deal.

**Comment by wraith321** [comment]
Why not just leave it as it is, I think it is perfectly fine:
trace_library.MASK_OPAQUE

**Comment by awilliamson** [comment]
Me and @Xandaros have decided to look at how several languages implement Enum types. We'll post more when we have it.

EDIT: 

http://stackoverflow.com/questions/287903/enums-in-javascript
http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Naming#Naming
http://stackoverflow.com/questions/1405851/enum-naming-convention-plural
http://stackoverflow.com/questions/3069743/coding-conventions-naming-enums

Based upon these links showcasing C#, Java and Javascript, we've decided to adopt the form of
`tracelib.enums.Mask.WATER` where enums is a table on the trace library to contain tables for the enum types. This is to prevent any potentially hazardous naming conflicting with existing lib code. Within enums will be the 'class' of enum and will follow Pascal casing, within that will be the actual enum which as always will be fully upercase.
