### ISSUE TITLE
Document all the things

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#84]
A lot of things are still undocumented. That needs to be fixed before initial release.
(Especially the player library. It is not documented at all.)

(Off-Topic: The getters in the player library don't have a "get" in front. We should fix that.)

**Comment by shadowscion** [comment]
I would like to help with this; but I don't know how to test the generations on my end before submitting a pull request.

**Comment by Xandaros** [comment]
Install the luadoc lua module and run build_docs.lua in the docgen directory.
If you are on Ubuntu or Debian, you can easily install it from the repository. On arch it is available in the AUR, I think. For other Linux distributions or platforms - no idea :P

**Comment by awilliamson** [comment]
On Arch be careful to run it with Lua 5.1. This will require you to find old 5.1 versions of LuaRocks and then the 5.1 of luadoc with its dependencies. Windows will be the same for LuaRocks, probably the easiest way.
