### ISSUE TITLE
Change entity folder names from gmod_wire...

### ISSUE THREAD

**Issue by awilliamson** [INPStarfall/Starfall#89]
Since we're planning on removing wire dependencies and gmod_wire_starfall_screen seems a bit too long I think we should name them to be a bit shorter and less of a mouthful.

Proposed naming:
- gmsf_NAME
- gmod_sf_NAME
- gmod_starfall_NAME
- sf_NAME
- starfall_NAME

I have a few preferences and some not. I prefer sf_NAME or starfall_NAME. There are however concerns of conflict is somebody in the future names things sf_.

**Comment by Xandaros** [comment]
I vote for starfall_NAME. sf_NAME might be shorter, but I think we should use a very distinct prefix.

Keep in mind this cannot be changed after initial release, because it would break dupes. Whatever we choose, it is permanent.
